### ISSUE TITLE
Priority matrix

### ISSUE THREAD

**Issue by dmsgnn** [DSD-DSec/backend#36]
## Description

The following feature aims to rank the tools used by the desc web service according to preferences expressed by the user. The ranking must be done every time a repo is created or updated and it must suggest only the most coherent tools.

## Requirements

- [ ] The Priority Matrix needs to access some Loading data (probably from Data.sql) about the tools. Each tool will have a row where there is its name and a score [1, 5] for every preference (this are the initial score given by us which represents the main functionality of the tool. E.g. a tool about static analysis will have security 5 but probably lower privacy score).
- [ ] The priority matrix will called by createRepo and updateRepo methods and must receive all the preferences of the user. Then the preferences of the user will be multiplied by the tool's values and ranked.
- [ ] The priority matrix will return a ranking about the tools and it will added in the json response using a "ranking" section in which there will be pairs "tool" : rank and a field "suggested" in which there will be how many tools must be suggested.

## Example

Loading data 
Tool              User Data         Security      Privacy         Language
Gitleaks               2                      5                 4                    null

Function call, with user preferences -> priority_matrix(type, domain, user data, security, privacy, language) 
E.g. -> priority_matrix(Website, Finance, false, 5, 3)

Score computation for each tool: Score = [((0 * userdata) || (1 * userdata)) + security * security + privacy * privacy ]
The score will become 0 if the language is not supported by the tool

## TODO 

- [ ] Field programming language must be added to repo
- [ ] Availability field must be replaced with privacy field, it makes more sense
